import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/**
 * Turns the automatic variant proposals into something a person can decide on.
 *
 *   pnpm --filter @apex/catalogue catalogue:variants-review
 *
 * The proposals are generated by matching a family word in the name — "squat",
 * "row", "curl" — and then linking *every* member of a family to every other.
 * That has two consequences, and the second is the one that matters:
 *
 * - A family of 19 produces 171 pairs. Nobody reviews 171 pairs.
 * - Membership is decided by a word, so the front squat, the jump squat and the
 *   rear-foot-elevated split squat end up declared variants of one another.
 *
 * This writes the clusters out with their pair counts, so the decision can be
 * taken per family rather than per pair, and marks the entries whose family
 * membership rests on nothing but the shared word.
 */

const root = fileURLToPath(new URL('../artifacts/curation/', import.meta.url));

const run = readdirSync(root)
  .map((name) => ({ name, at: statSync(`${root}${name}`).mtimeMs }))
  .sort((a, b) => b.at - a.at)[0]?.name;

if (run === undefined) throw new Error('No curation run to read.');

interface Entry {
  key: string;
  name: string;
  canonicalName: string;
  category: string;
  primaryMuscles: string[];
  equipment: string[];
  movementPattern: string;
  unilateral: boolean;
}

const read = <T>(file: string): T => JSON.parse(readFileSync(`${root}${run}/${file}`, 'utf8')) as T;

const exercises = read<{ exercises: Entry[] }>('selection.json').exercises;
const pairs = read<{ pairs: { a: string; b: string; basis: string }[] }>('variants.json').pairs;

const byKey = new Map(exercises.map((entry) => [entry.key, entry]));

// ── Clusters ─────────────────────────────────────────────────────────────────

const neighbours = new Map<string, Set<string>>();

for (const pair of pairs) {
  for (const [a, b] of [
    [pair.a, pair.b],
    [pair.b, pair.a],
  ] as const) {
    if (!neighbours.has(a)) neighbours.set(a, new Set());
    neighbours.get(a)?.add(b);
  }
}

const seen = new Set<string>();
const clusters: Entry[][] = [];

for (const start of neighbours.keys()) {
  if (seen.has(start)) continue;

  const stack = [start];
  const members: string[] = [];
  seen.add(start);

  while (stack.length > 0) {
    const current = stack.pop() ?? '';
    members.push(current);

    for (const next of neighbours.get(current) ?? []) {
      if (seen.has(next)) continue;
      seen.add(next);
      stack.push(next);
    }
  }

  const entries = members.flatMap((key) => {
    const entry = byKey.get(key);

    return entry === undefined ? [] : [entry];
  });

  if (entries.length > 0) clusters.push(entries);
}

clusters.sort((a, b) => b.length - a.length);

/**
 * Movements that differ in more than the implement.
 *
 * Within a family, an exercise sharing the *movement pattern* of the others is
 * a plausible variant — barbell and dumbbell rows are both horizontal pulls. An
 * exercise that joined on the family word while doing something else entirely is
 * the case worth marking: a jump squat in the squat family is a plyometric.
 */
const dominantPattern = (cluster: readonly Entry[]): string => {
  const counts = new Map<string, number>();
  for (const entry of cluster) {
    counts.set(entry.movementPattern, (counts.get(entry.movementPattern) ?? 0) + 1);
  }

  return [...counts.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? '';
};

// ── Duplicate candidates ─────────────────────────────────────────────────────

/**
 * Two exercises a coach would struggle to tell apart in a picker: same category,
 * same primary muscles, same equipment, same movement pattern.
 *
 * Unlike the variant proposals this is not a naming heuristic — it compares what
 * the entries claim to *be*. It still is not a verdict: a flat and an incline
 * press legitimately match on all four.
 */
const signature = (entry: Entry) =>
  [
    entry.category,
    entry.movementPattern,
    [...entry.primaryMuscles].sort().join(','),
    [...entry.equipment].sort().join(','),
    entry.unilateral ? 'ein' : 'beid',
  ].join(' | ');

const bySignature = new Map<string, Entry[]>();

for (const entry of exercises) {
  const group = bySignature.get(signature(entry)) ?? [];
  group.push(entry);
  bySignature.set(signature(entry), group);
}

const indistinguishable = [...bySignature.entries()]
  .filter(([, group]) => group.length > 1)
  .sort((a, b) => b[1].length - a[1].length);

/**
 * The narrower question: same claims *and* nearly the same name.
 *
 * Matching attributes alone was measured and found unusable — it groups the
 * sit-up with the hanging leg raise, which are plainly different exercises. What
 * separates a genuine duplicate is that the names also overlap: "Liegendes
 * hinteres Seitheben" and "Liegendes hinteres Seitheben mit Kurzhanteln" are one
 * exercise written twice.
 */
const NAME_NOISE = new Set(['mit', 'am', 'im', 'auf', 'in', 'der', 'die', 'das', 'einer', 'dem']);

const words = (entry: Entry) =>
  new Set(
    entry.name
      .toLowerCase()
      .replace(/[^a-zäöüß ]/g, ' ')
      .split(/\s+/)
      .filter((word) => word.length > 2 && !NAME_NOISE.has(word)),
  );

const overlap = (a: Entry, b: Entry): number => {
  const first = words(a);
  const second = words(b);
  const shared = [...first].filter((word) => second.has(word)).length;

  return shared / Math.min(first.size, second.size);
};

const candidates = exercises.flatMap((a, index) =>
  exercises.slice(index + 1).flatMap((b) => {
    // Either the data cannot tell them apart, or the names nearly coincide —
    // both together is what makes a pair worth opening.
    const sameClaims = signature(a) === signature(b);
    const sameWords = overlap(a, b);

    return sameClaims && sameWords >= 0.6 ? [{ a, b, sameWords }] : [];
  }),
);

// ── Write ────────────────────────────────────────────────────────────────────

const markdown = `# Varianten und Dubletten — zur Entscheidung

Lauf \`${run}\`. **Nichts hiervon ist in der Datenbank**, und dieses Dokument
ändert nichts.

---

## Teil 1 — Warum die ${String(pairs.length)} Variantenvorschläge nicht brauchbar sind

Die Vorschläge entstehen so: Ein Familienwort im englischen Namen — \`squat\`,
\`row\`, \`curl\` — bildet eine Gruppe, und **jedes Mitglied wird mit jedem
anderen verknüpft**. Daraus folgen zwei Dinge.

**Erstens die Menge.** Eine Familie mit 19 Übungen erzeugt 171 Paare. Die
${String(pairs.length)} Vorschläge verteilen sich auf nur ${String(clusters.length)} Familien:

| Familie | Übungen | Paare |
| --- | --- | --- |
${clusters
  .map(
    (cluster) =>
      `| ${dominantPattern(cluster)} | ${String(cluster.length)} | ${String((cluster.length * (cluster.length - 1)) / 2)} |`,
  )
  .join('\n')}

**Zweitens, und das ist der eigentliche Fehler:** Die Zugehörigkeit hängt am
Wort, nicht an der Bewegung. In der Kniebeugen-Familie steht die Sprungkniebeuge
neben der Frontkniebeuge und dem Split Squat — drei verschiedene Trainingsziele,
verbunden durch die Silbe „Squat".

Das verletzt die Regel, die Sie selbst gesetzt haben: *keine Varianten aufgrund
bloßer Namensähnlichkeit.*

### Was zur Entscheidung steht

- **A — Alles verwerfen und von Hand setzen.** Die Familien, die in der Review
  ohnehin entstanden sind (Bankdrücken, Kreuzheben, Rudern, Umsetzen, Kniebeuge),
  sind fachlich gesichert. Aufwand: ein Arbeitsschritt, überschaubar.
- **B — Familienweise freigeben und einzeln ausdünnen.** Sie gehen die Listen
  unten durch und streichen, was nicht zusammengehört.
- **C — Varianten vorerst leer lassen.** Der Katalog funktioniert ohne sie; das
  Feld bleibt für später.

---

${clusters
  .map((cluster, index) => {
    const pattern = dominantPattern(cluster);
    const sorted = [...cluster].sort((a, b) => a.name.localeCompare(b.name, 'de'));

    return `### Familie ${String(index + 1)} · ${String(cluster.length)} Übungen · ${String((cluster.length * (cluster.length - 1)) / 2)} Paare

Vorherrschendes Muster: \`${pattern}\`

| ✓ | Übung | Muster | Kategorie | primäre Muskeln | Equipment |
| --- | --- | --- | --- | --- | --- |
${sorted
  .map(
    (entry) =>
      `| [ ] | ${entry.name} | ${entry.movementPattern === pattern ? entry.movementPattern : `**${entry.movementPattern}**`} | ${entry.category} | ${entry.primaryMuscles.join(', ')} | ${entry.equipment.join(', ') || 'Körpergewicht'} |`,
  )
  .join('\n')}

_Fett gesetzte Muster weichen von der Familie ab — dort ist die Zuordnung am
wahrscheinlichsten falsch._`;
  })
  .join('\n\n')}

---

## Teil 2 — Dublettenkandidaten

**${String(candidates.length)} Paare.** Diese teilen sowohl alles, was die Daten über sie sagen —
Kategorie, Bewegungsmuster, primäre Muskeln, Equipment, Seitigkeit — **als auch**
den Großteil ihres Namens. Das ist das Bild einer Übung, die zweimal im Katalog
steht.

${
  candidates.length === 0
    ? '_Keine._'
    : candidates
        .map(
          (pair) =>
            `- [ ] **${pair.a.name}** ↔ **${pair.b.name}**\n  \`${pair.a.canonicalName}\` ↔ \`${pair.b.canonicalName}\``,
        )
        .join('\n')
}

### Ein Befund ohne Entscheidungsbedarf

${String(indistinguishable.reduce((sum, [, group]) => sum + group.length, 0))} Übungen in ${String(indistinguishable.length)} Gruppen sind **anhand ihrer strukturierten
Daten nicht unterscheidbar** — gleiche Kategorie, gleiches Muster, gleiche
Muskeln, gleiches Equipment. Der Unterschied steht nur im Namen und in den
Instructions.

Das sind überwiegend legitim verschiedene Übungen: Sit-up, reverser Crunch und
hängendes Beinheben stehen alle drei auf \`strength | trunk_flexion | abs\`. Es
heißt nur, dass ein Filter über Kategorie und Muskeln sie nebeneinander ausgibt
und der Coach am Namen entscheidet. Für den MVP ist das in Ordnung — es ist
erwähnenswert, falls später eine feinere Suche gewünscht wird.

<details>
<summary>Die ${String(indistinguishable.length)} Gruppen im Einzelnen</summary>

${indistinguishable
  .map(([key, group]) => `**${key}** — ${group.map((entry) => entry.name).join(' · ')}`)
  .join('\n\n')}

</details>

---

## So gehen Sie damit um

Kreuzen Sie an, was **entfernt** oder **zusammengeführt** werden soll, und
schreiben Sie dahinter, was stattdessen gelten soll. Ich arbeite es in einen
neuen Lauf ein — der jetzige bleibt als Zwischenstand erhalten.

Für Teil 1 genügt mir Ihre Entscheidung A, B oder C; die Einzelabhaken sind nur
nötig, wenn Sie B wählen.
`;

writeFileSync(`${root}${run}/VARIANTS_REVIEW.md`, markdown, 'utf8');

console.info('');
console.info(`Geschrieben: artifacts/curation/${run}/VARIANTS_REVIEW.md`);
console.info(
  `  ${String(pairs.length)} Vorschläge in ${String(clusters.length)} Familien, größte ${String(clusters[0]?.length ?? 0)} Übungen`,
);
console.info(
  `  ${String(candidates.length)} Dublettenkandidaten, ${String(indistinguishable.length)} Gruppen ohne unterscheidende Daten`,
);
console.info('  Nichts geändert, nichts in die Datenbank geschrieben.');
