import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/**
 * Which review block an exercise belongs to, frozen once and kept.
 *
 * The blocks used to be cut from the list sorted by German name. Renaming an
 * exercise then moved it: after block 1 changed eleven names, six reviewed
 * exercises had slid out of block 1 — "Wadenheben mit Band" landed at position
 * 133 — and six unreviewed ones had slid in. A review whose blocks reshuffle
 * between runs cannot be completed, because "block 2" means something different
 * each time it is opened.
 *
 * So membership is assigned once, stored against `canonicalName`, and never
 * recomputed. The English technical name is the identifier that survives the
 * renaming; the German display name is exactly what changes.
 *
 * New exercises entering a later run are appended to the end — never inserted
 * into a block somebody has already worked through.
 *
 * The file lives at the package root rather than under `artifacts/`, because
 * artefacts are generated and disposable and this is neither: losing it would
 * scramble the block numbering the review is conducted in.
 */

const file = fileURLToPath(new URL('../../review-batches.json', import.meta.url));

export interface Batch {
  readonly block: number;
  readonly title: string;
  /** Canonical names, in the order the block was first laid out. */
  readonly exercises: readonly string[];
}

interface BatchFile {
  readonly version: number;
  readonly note: string;
  readonly blocks: readonly Batch[];
}

export const readBatches = (): readonly Batch[] =>
  existsSync(file) ? (JSON.parse(readFileSync(file, 'utf8')) as BatchFile).blocks : [];

export const writeBatches = (blocks: readonly Batch[]): void =>
  writeFileSync(
    file,
    `${JSON.stringify(
      {
        version: 1,
        note: 'Frozen review-block membership, keyed by canonicalName. Renaming an exercise must not move it between blocks. Generated by scripts/review-batches.ts; edit only to correct a mistake.',
        blocks,
      },
      null,
      2,
    )}\n`,
    'utf8',
  );

export interface Assignable {
  readonly canonicalName: string;
  readonly category: string;
}

/**
 * Extends the frozen assignment with whatever is new, leaving the rest alone.
 *
 * Three properties this has to hold, and each is tested:
 *
 * - an exercise already assigned keeps its block, whatever it is now called;
 * - an exercise appears in exactly one block;
 * - an exercise that has left the selection leaves the assignment, so a block
 *   never lists a row the catalogue no longer has.
 */
export function assignBatches(
  existing: readonly Batch[],
  exercises: readonly Assignable[],
  options: { readonly maximum: number; readonly label: (category: string) => string },
): readonly Batch[] {
  const present = new Set(exercises.map((entry) => entry.canonicalName));
  const assigned = new Map<string, number>();

  const blocks = existing.map((batch) => {
    const kept = batch.exercises.filter((name) => present.has(name));
    for (const name of kept) assigned.set(name, batch.block);

    return { ...batch, exercises: kept };
  });

  const unassigned = exercises.filter((entry) => !assigned.has(entry.canonicalName));
  if (unassigned.length === 0) return blocks.filter((batch) => batch.exercises.length > 0);

  const result = [...blocks];
  let next = Math.max(0, ...result.map((batch) => batch.block)) + 1;

  // New exercises are grouped by category and appended. They never top up an
  // existing block: adding a row to a block already signed off would mean the
  // sign-off no longer covers what the block contains.
  const categories = [...new Set(unassigned.map((entry) => entry.category))];

  for (const category of categories) {
    const group = unassigned.filter((entry) => entry.category === category);
    const count = Math.max(1, Math.ceil(group.length / options.maximum));
    const size = Math.ceil(group.length / count);

    for (let i = 0; i < count; i++) {
      const slice = group.slice(i * size, (i + 1) * size);
      if (slice.length === 0) continue;

      result.push({
        block: next,
        title:
          count === 1
            ? options.label(category)
            : `${options.label(category)} – Teil ${String(i + 1)}`,
        exercises: slice.map((entry) => entry.canonicalName),
      });
      next += 1;
    }
  }

  return result.filter((batch) => batch.exercises.length > 0);
}
